name: github_card
version: 0.1.0+1
author: Frederik Leonhardt <frederik.leonhardt@gmail.com>
homepage: https://github.com/fkleon/github_card
description: A polymer web component to show a profile card for your Github account.
dependencies:
  polymer: ">=0.15.0+1 <0.16.0"
  github: ">=2.1.1 <2.2.0"
transformers:
- polymer:
    entry_points: example/demo.html